import { AppHeader } from "@/components/app-header";
import { Button } from "@/components/ui/button";
import { Field, FormCard, Pager, SearchFilters, selectClass, StatusBadge } from "@/components/operational/operational-ui";
import { hasPermission } from "@/server/authorization/permissions";
import { listUnits } from "@/server/operational/operational-service";
import { requireActiveTenantForPage } from "@/server/tenancy/page-context";
import { createUnitAction, updateUnitAction } from "@/app/operational-actions";

export const dynamic = "force-dynamic";
export const metadata = { title: "Unidades" };

export default async function UnitsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const context = await requireActiveTenantForPage();
  const data = await listUnits(context, await searchParams);
  const canCreate = hasPermission(context.permissions, "units.create");
  const canUpdate = hasPermission(context.permissions, "units.update");
  return <main className="min-h-screen bg-muted"><AppHeader tenantName={context.tenantName} permissions={context.permissions} /><section className="mx-auto grid max-w-7xl gap-6 px-5 py-8 sm:px-8"><header><p className="text-sm font-medium text-primary">Estrutura operacional</p><h1 className="mt-1 text-3xl font-bold">Unidades</h1><p className="mt-2 text-muted-foreground">Filiais, bases, depósitos e estabelecimentos deste tenant.</p></header><SearchFilters statusOptions={["ACTIVE", "INACTIVE", "ARCHIVED"]} />{canCreate && <FormCard title="Nova unidade"><UnitForm action={createUnitAction} submit="Criar unidade" /></FormCard>}<div className="grid gap-4">{data.items.length === 0 ? <div className="rounded-xl border border-dashed bg-background p-10 text-center text-muted-foreground">Nenhuma unidade encontrada.</div> : data.items.map((unit) => <article className="rounded-xl border bg-background p-5" key={unit.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{unit.name}</h2><p className="text-sm text-muted-foreground">{unit.code} · {[unit.city, unit.state].filter(Boolean).join(" / ") || "Endereço não informado"}</p></div><StatusBadge>{unit.status}</StatusBadge></div>{canUpdate && <details className="mt-4 border-t pt-4"><summary className="cursor-pointer text-sm font-semibold">Editar</summary><div className="mt-4"><UnitForm action={updateUnitAction.bind(null, unit.id)} submit="Salvar alterações" unit={unit} /></div></details>}</article>)}</div><Pager page={data.page} pageSize={data.pageSize} pathname="/units" total={data.total} /></section></main>;
}

function UnitForm({ action, submit, unit }: { action: (form: FormData) => Promise<void>; submit: string; unit?: { name: string; code: string; status: string; phone: string | null; email: string | null; addressLine1: string | null; addressLine2: string | null; city: string | null; state: string | null; postalCode: string | null; country: string } }) {
  return <form action={action} className="grid gap-4 md:grid-cols-2"><Field label="Nome" name="name" required><input className={selectClass} defaultValue={unit?.name} id="name" name="name" required /></Field><Field label="Código" name="code" required><input className={selectClass} defaultValue={unit?.code} id="code" name="code" required /></Field><Field label="Status" name="status"><select className={selectClass} defaultValue={unit?.status ?? "ACTIVE"} id="status" name="status"><option>ACTIVE</option><option>INACTIVE</option><option>ARCHIVED</option></select></Field><Field label="Telefone" name="phone"><input className={selectClass} defaultValue={unit?.phone ?? ""} id="phone" name="phone" /></Field><Field label="E-mail" name="email"><input className={selectClass} defaultValue={unit?.email ?? ""} id="email" name="email" type="email" /></Field><Field label="Endereço" name="addressLine1"><input className={selectClass} defaultValue={unit?.addressLine1 ?? ""} id="addressLine1" name="addressLine1" /></Field><Field label="Complemento" name="addressLine2"><input className={selectClass} defaultValue={unit?.addressLine2 ?? ""} id="addressLine2" name="addressLine2" /></Field><Field label="Cidade" name="city"><input className={selectClass} defaultValue={unit?.city ?? ""} id="city" name="city" /></Field><Field label="Estado" name="state"><input className={selectClass} defaultValue={unit?.state ?? ""} id="state" name="state" /></Field><Field label="CEP" name="postalCode"><input className={selectClass} defaultValue={unit?.postalCode ?? ""} id="postalCode" name="postalCode" /></Field><Field label="País" name="country"><input className={selectClass} defaultValue={unit?.country ?? "BR"} id="country" maxLength={2} name="country" /></Field><Button className="md:col-span-2 md:justify-self-start" type="submit">{submit}</Button></form>;
}
