import { createHash, randomUUID } from "node:crypto";
import type { EvidenceType } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/server/authorization/permissions";
import { AppError } from "@/server/errors/app-error";
import type { OperationalContext } from "@/server/operational/service-helpers";
import { localStorageProvider } from "@/server/storage/local-storage-provider";
import type { StorageProvider } from "@/server/storage/storage-provider";
export const EVIDENCE_MAX_BYTES = 8 * 1024 * 1024;
const allowed = new Map([["image/jpeg", [0xff,0xd8,0xff]], ["image/png", [0x89,0x50,0x4e,0x47]], ["image/webp", [0x52,0x49,0x46,0x46]]]);
export function validateEvidence(content: Uint8Array, mimeType: string) { const magic = allowed.get(mimeType); if (!magic || content.byteLength === 0 || content.byteLength > EVIDENCE_MAX_BYTES || !magic.every((b,i) => content[i] === b)) throw new AppError("VALIDATION_ERROR", "Evidência inválida. Use JPEG, PNG ou WebP de até 8 MB."); }
export async function addPickupEvidence(context: OperationalContext, input: { pickupId: string; pickupItemId?: string; type: EvidenceType; content: Uint8Array; mimeType: string }, storage: StorageProvider = localStorageProvider) { requirePermission(context.permissions, "pickups.add_evidence"); validateEvidence(input.content, input.mimeType); const pickup = await prisma.reservationPickup.findFirst({ where: { id: input.pickupId, tenantId: context.tenantId }, include: { items: { select: { id: true } } } }); if (!pickup || (input.pickupItemId && !pickup.items.some(i => i.id === input.pickupItemId))) throw new AppError("NOT_FOUND", "Retirada não encontrada."); const checksum = createHash("sha256").update(input.content).digest("hex"); const key = `${context.tenantId}/${input.pickupId}/${randomUUID()}`; await storage.put(key, input.content, input.mimeType); try { const evidence = await prisma.operationalEvidence.create({ data: { tenantId: context.tenantId, pickupId: input.pickupId, pickupItemId: input.pickupItemId, type: input.type, storageKey: key, mimeType: input.mimeType, size: input.content.byteLength, checksum, uploadedByUserId: context.user.id } }); await prisma.auditLog.create({ data: { scope: "TENANT", tenantId: context.tenantId, actorUserId: context.user.id, action: "pickup.evidence_added", entityType: "ReservationPickup", entityId: input.pickupId, metadata: { evidenceId: evidence.id, type: input.type } } }); return evidence; } catch (error) { await storage.delete(key); throw error; } }
export async function readPickupEvidence(context: OperationalContext, evidenceId: string, storage: StorageProvider = localStorageProvider) { requirePermission(context.permissions, "pickups.view_evidence"); const evidence = await prisma.operationalEvidence.findFirst({ where: { id: evidenceId, tenantId: context.tenantId } }); if (!evidence) throw new AppError("NOT_FOUND", "Evidência não encontrada."); return { evidence, content: await storage.get(evidence.storageKey) }; }
