import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/server/authorization/permissions";
import { AppError } from "@/server/errors/app-error";
import type { OperationalContext } from "@/server/operational/service-helpers";
import { requirePickupEligibility } from "./pickup-policy";
import { inspectionSchema, pickupListSchema, refusalSchema, startPickupSchema } from "./pickup-validation";

const notFound = () => new AppError("NOT_FOUND", "Retirada ou reserva não encontrada.");
const conflict = () => new AppError("CONFLICT", "A retirada foi alterada por outra operação ou já foi concluída.");
function mapError(error: unknown): never { if (error instanceof AppError) throw error; if (error instanceof Prisma.PrismaClientKnownRequestError && ["P2002", "P2034"].includes(error.code)) throw conflict(); if (error instanceof Error && /deadlock|40P01|unique|concurrent/i.test(error.message)) throw conflict(); throw error; }
const audit = (context: OperationalContext, action: string, id: string, metadata?: Prisma.InputJsonValue) => ({ scope: "TENANT" as const, tenantId: context.tenantId, actorUserId: context.user.id, action, entityType: "ReservationPickup", entityId: id, metadata });

export async function startPickup(context: OperationalContext, reservationId: string, raw: unknown) {
  requirePermission(context.permissions, "pickups.start"); const input = startPickupSchema.parse(raw);
  try { return await prisma.$transaction(async (tx) => {
    const reservation = await tx.reservation.findFirst({ where: { id: reservationId, tenantId: context.tenantId }, include: { items: true, pickups: { where: { status: { in: ["IN_PROGRESS", "COMPLETED"] } }, select: { id: true } } } });
    if (!reservation) throw notFound(); requirePickupEligibility(reservation.status, reservation.startAt); if (reservation.pickups.length) throw conflict();
    if (reservation.status === "CONFIRMED") { const changed = await tx.reservation.updateMany({ where: { id: reservation.id, tenantId: context.tenantId, status: "CONFIRMED" }, data: { status: "READY_FOR_PICKUP" } }); if (changed.count !== 1) throw conflict(); await tx.reservationItem.updateMany({ where: { reservationId: reservation.id, tenantId: context.tenantId }, data: { status: "READY_FOR_PICKUP" } }); await tx.reservationStatusHistory.create({ data: { tenantId: context.tenantId, reservationId, fromStatus: "CONFIRMED", toStatus: "READY_FOR_PICKUP", actorUserId: context.user.id } }); }
    const pickup = await tx.reservationPickup.create({ data: { tenantId: context.tenantId, reservationId, processedByUserId: context.user.id, ...input } });
    await tx.reservationPickupItem.createMany({ data: reservation.items.map((item) => ({ tenantId: context.tenantId, pickupId: pickup.id, reservationItemId: item.id, resourceId: item.resourceId })) });
    await tx.auditLog.create({ data: audit(context, "pickup.started", pickup.id, { reservationId, itemCount: reservation.items.length }) }); return pickup;
  }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); } catch (e) { mapError(e); }
}

export async function inspectPickup(context: OperationalContext, pickupId: string, raw: unknown) {
  requirePermission(context.permissions, "pickups.inspect"); const input = inspectionSchema.parse(raw);
  return prisma.$transaction(async (tx) => { const pickup = await tx.reservationPickup.findFirst({ where: { id: pickupId, tenantId: context.tenantId, status: "IN_PROGRESS" }, include: { items: true } }); if (!pickup) throw notFound(); const expected = new Set(pickup.items.map(({ id }) => id)); if (input.items.length !== expected.size || input.items.some(({ pickupItemId }) => !expected.has(pickupItemId))) throw new AppError("VALIDATION_ERROR", "A conferência deve incluir exatamente todos os recursos esperados."); for (const item of input.items) await tx.reservationPickupItem.update({ where: { id: item.pickupItemId }, data: { condition: item.condition, notes: item.notes, checkedAt: new Date(), checkedByUserId: context.user.id } }); await tx.auditLog.create({ data: audit(context, "pickup.item_checked", pickupId, { itemCount: input.items.length }) }); });
}

export async function refusePickup(context: OperationalContext, pickupId: string, raw: unknown) {
  requirePermission(context.permissions, "pickups.refuse"); const input = refusalSchema.parse(raw);
  return prisma.$transaction(async (tx) => { const changed = await tx.reservationPickup.updateMany({ where: { id: pickupId, tenantId: context.tenantId, status: "IN_PROGRESS" }, data: { status: "REFUSED", refusedAt: new Date(), refusalReasonCode: input.reasonCode, refusalNotes: input.notes } }); if (changed.count !== 1) throw conflict(); await tx.reservationPickupItem.updateMany({ where: { pickupId, tenantId: context.tenantId }, data: { status: "REFUSED" } }); await tx.auditLog.create({ data: audit(context, "pickup.refused", pickupId, input) }); });
}

export async function completePickup(context: OperationalContext, pickupId: string) {
  requirePermission(context.permissions, "pickups.complete");
  try { return await prisma.$transaction(async (tx) => { const pickup = await tx.reservationPickup.findFirst({ where: { id: pickupId, tenantId: context.tenantId }, include: { reservation: true, items: true } }); if (!pickup) throw notFound(); if (pickup.status !== "IN_PROGRESS" || pickup.items.some((i) => !i.checkedAt || i.condition !== "OK")) throw conflict(); const changed = await tx.reservationPickup.updateMany({ where: { id: pickupId, tenantId: context.tenantId, status: "IN_PROGRESS" }, data: { status: "COMPLETED", completedAt: new Date() } }); if (changed.count !== 1) throw conflict(); const reservationChanged = await tx.reservation.updateMany({ where: { id: pickup.reservationId, tenantId: context.tenantId, status: "READY_FOR_PICKUP" }, data: { status: "RELEASED" } }); if (reservationChanged.count !== 1) throw conflict(); await tx.reservationPickupItem.updateMany({ where: { pickupId, tenantId: context.tenantId }, data: { status: "RELEASED" } }); await tx.reservationItem.updateMany({ where: { reservationId: pickup.reservationId, tenantId: context.tenantId }, data: { status: "RELEASED" } }); await tx.reservationStatusHistory.create({ data: { tenantId: context.tenantId, reservationId: pickup.reservationId, fromStatus: "READY_FOR_PICKUP", toStatus: "RELEASED", actorUserId: context.user.id } }); await tx.resource.updateMany({ where: { id: { in: pickup.items.map(i => i.resourceId) }, tenantId: context.tenantId }, data: { operationalStatus: "IN_USE" } }); await tx.resourceCustodyEvent.createMany({ data: pickup.items.map(i => ({ tenantId: context.tenantId, resourceId: i.resourceId, reservationId: pickup.reservationId, pickupId, type: "RELEASED_TO_RECIPIENT", fromParty: pickup.reservation.unitId, toParty: pickup.recipientName, actorUserId: context.user.id })) }); await tx.auditLog.create({ data: audit(context, "pickup.completed", pickupId, { recipientName: pickup.recipientName, itemCount: pickup.items.length }) }); return tx.reservationPickup.findUniqueOrThrow({ where: { id: pickupId } }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); } catch (e) { mapError(e); }
}

export async function listPickupQueue(context: OperationalContext, raw: unknown = {}) { requirePermission(context.permissions, "pickups.view"); const q = pickupListSchema.parse(raw); return prisma.reservation.findMany({ where: { tenantId: context.tenantId, status: { in: ["CONFIRMED", "READY_FOR_PICKUP", "RELEASED"] }, ...(q.urgent ? { isUrgent: q.urgent === "true" } : {}), ...(q.search ? { OR: [{ code: { contains: q.search, mode: "insensitive" } }, { customer: { legalName: { contains: q.search, mode: "insensitive" } } }] } : {}), ...(q.status === "completed" ? { pickups: { some: { status: "COMPLETED" } } } : q.status === "refused" ? { pickups: { some: { status: "REFUSED" } } } : {}) }, include: { customer: true, unit: true, pickups: { orderBy: { createdAt: "desc" } }, _count: { select: { items: true } } }, orderBy: [{ isUrgent: "desc" }, { startAt: "asc" }] }); }
export async function getPickup(context: OperationalContext, id: string) { requirePermission(context.permissions, "pickups.view"); const result = await prisma.reservationPickup.findFirst({ where: { id, tenantId: context.tenantId }, include: { reservation: { include: { customer: true, unit: true } }, processedBy: { select: { name: true, email: true } }, items: { include: { resource: true } }, evidence: true, custodyEvents: true } }); if (!result) throw notFound(); return result; }
