import Link from "next/link";
import { AppHeader } from "@/components/app-header";
import { Button } from "@/components/ui/button";
import { Field, FormCard, Pager, SearchFilters, selectClass, StatusBadge, textareaClass } from "@/components/operational/operational-ui";
import { createCustomerAction, updateCustomerAction } from "@/app/operational-actions";
import { hasPermission } from "@/server/authorization/permissions";
import { listCustomers } from "@/server/operational/operational-service";
import { requireActiveTenantForPage } from "@/server/tenancy/page-context";

export const dynamic = "force-dynamic";
export const metadata = { title: "Clientes" };

export default async function CustomersPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const context = await requireActiveTenantForPage();
  const data = await listCustomers(context, await searchParams);
  const canCreate = hasPermission(context.permissions, "customers.create");
  const canUpdate = hasPermission(context.permissions, "customers.update");
  return <main className="min-h-screen bg-muted"><AppHeader tenantName={context.tenantName} permissions={context.permissions} /><section className="mx-auto grid max-w-7xl gap-6 px-5 py-8 sm:px-8"><header><p className="text-sm font-medium text-primary">Relacionamento comercial</p><h1 className="mt-1 text-3xl font-bold">Clientes</h1><p className="mt-2 text-muted-foreground">Cadastro tenant-aware com contatos, endereços e histórico contratual preservado.</p></header><SearchFilters statusOptions={["ACTIVE", "INACTIVE", "ARCHIVED"]} />{canCreate && <FormCard title="Novo cliente"><CustomerForm action={createCustomerAction} submit="Criar cliente" /></FormCard>}<div className="grid gap-4 md:grid-cols-2">{data.items.length === 0 ? <div className="rounded-xl border border-dashed bg-background p-10 text-center text-muted-foreground md:col-span-2">Nenhum cliente encontrado.</div> : data.items.map((customer) => <article className="rounded-xl border bg-background p-5" key={customer.id}><div className="flex items-start justify-between gap-3"><div><Link className="font-semibold text-primary hover:underline" href={`/customers/${customer.id}`}>{customer.legalName}</Link><p className="text-sm text-muted-foreground">{customer.tradeName ?? customer.type} · {customer.document ?? "Documento não informado"}</p></div><StatusBadge>{customer.status}</StatusBadge></div><p className="mt-3 text-sm">{customer.email ?? customer.phone ?? "Contato geral não informado"}</p><p className="mt-1 text-xs text-muted-foreground">{customer._count.contracts} contrato(s) · {customer.contacts.length} contato(s)</p>{canUpdate && <details className="mt-4 border-t pt-4"><summary className="cursor-pointer text-sm font-semibold">Editar</summary><div className="mt-4"><CustomerForm action={updateCustomerAction.bind(null, customer.id)} customer={customer} submit="Salvar alterações" /></div></details>}</article>)}</div><Pager page={data.page} pageSize={data.pageSize} pathname="/customers" total={data.total} /></section></main>;
}

function CustomerForm({ action, submit, customer }: { action: (form: FormData) => Promise<void>; submit: string; customer?: { type: string; legalName: string; tradeName: string | null; document: string | null; status: string; email: string | null; phone: string | null; notes: string | null } }) {
  return <form action={action} className="grid gap-4 md:grid-cols-2"><Field label="Tipo" name="type"><select className={selectClass} defaultValue={customer?.type ?? "COMPANY"} id="type" name="type"><option value="COMPANY">Pessoa jurídica</option><option value="INDIVIDUAL">Pessoa física</option></select></Field><Field label="Nome legal" name="legalName" required><input className={selectClass} defaultValue={customer?.legalName} id="legalName" name="legalName" required /></Field><Field label="Nome comercial" name="tradeName"><input className={selectClass} defaultValue={customer?.tradeName ?? ""} id="tradeName" name="tradeName" /></Field><Field label="Documento" name="document"><input className={selectClass} defaultValue={customer?.document ?? ""} id="document" name="document" /></Field><Field label="Status" name="status"><select className={selectClass} defaultValue={customer?.status ?? "ACTIVE"} id="status" name="status"><option>ACTIVE</option><option>INACTIVE</option><option>ARCHIVED</option></select></Field><Field label="E-mail" name="email"><input className={selectClass} defaultValue={customer?.email ?? ""} id="email" name="email" type="email" /></Field><Field label="Telefone" name="phone"><input className={selectClass} defaultValue={customer?.phone ?? ""} id="phone" name="phone" /></Field><Field label="Observações" name="notes"><textarea className={textareaClass} defaultValue={customer?.notes ?? ""} id="notes" name="notes" /></Field><Button className="md:col-span-2 md:justify-self-start" type="submit">{submit}</Button></form>;
}
