CREATE TYPE "AcceptanceMethod" AS ENUM ('DRAWN_SIGNATURE','OTP_WHATSAPP','OTP_SMS','OTP_EMAIL');
CREATE TYPE "AcceptanceStatus" AS ENUM ('PENDING','VERIFIED','EXPIRED','CANCELLED','FAILED');
CREATE TYPE "OtpChallengeStatus" AS ENUM ('PENDING','VERIFIED','EXPIRED','INVALIDATED','BLOCKED');
CREATE TYPE "OtpChannel" AS ENUM ('WHATSAPP','SMS','EMAIL');
CREATE TYPE "OtpDeliveryStatus" AS ENUM ('SENT','FAILED');
CREATE TABLE "PickupAcceptance" ("id" UUID PRIMARY KEY,"tenantId" UUID NOT NULL,"pickupId" UUID NOT NULL,"method" "AcceptanceMethod" NOT NULL,"status" "AcceptanceStatus" NOT NULL DEFAULT 'PENDING',"signerName" TEXT NOT NULL,"signerDocument" TEXT,"signerPhone" TEXT,"signerEmail" TEXT,"termsVersion" TEXT NOT NULL,"termsHash" TEXT NOT NULL,"termsSnapshot" TEXT NOT NULL,"acceptedAt" TIMESTAMPTZ(3),"expiresAt" TIMESTAMPTZ(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "PickupOtpChallenge" ("id" UUID PRIMARY KEY,"tenantId" UUID NOT NULL,"acceptanceId" UUID NOT NULL,"channel" "OtpChannel" NOT NULL,"destinationMasked" TEXT NOT NULL,"destinationHash" TEXT NOT NULL,"codeHash" TEXT NOT NULL,"status" "OtpChallengeStatus" NOT NULL DEFAULT 'PENDING',"attempts" INTEGER NOT NULL DEFAULT 0,"maxAttempts" INTEGER NOT NULL DEFAULT 5,"expiresAt" TIMESTAMPTZ(3) NOT NULL,"sentAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"verifiedAt" TIMESTAMPTZ(3),"invalidatedAt" TIMESTAMPTZ(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "OtpDeliveryAttempt" ("id" UUID PRIMARY KEY,"tenantId" UUID NOT NULL,"challengeId" UUID NOT NULL,"channel" "OtpChannel" NOT NULL,"provider" TEXT NOT NULL,"status" "OtpDeliveryStatus" NOT NULL,"providerMessageId" TEXT,"errorCode" TEXT,"sentAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AcceptanceSignature" ("id" UUID PRIMARY KEY,"tenantId" UUID NOT NULL,"acceptanceId" UUID NOT NULL,"storageKey" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"size" INTEGER NOT NULL,"checksum" TEXT NOT NULL,"width" INTEGER NOT NULL,"height" INTEGER NOT NULL,"capturedByUserId" UUID NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "PickupAcceptance_tenantId_id_key" ON "PickupAcceptance"("tenantId","id");
CREATE INDEX "PickupAcceptance_tenantId_pickupId_status_idx" ON "PickupAcceptance"("tenantId","pickupId","status");
CREATE UNIQUE INDEX "PickupAcceptance_one_verified_per_pickup" ON "PickupAcceptance"("tenantId","pickupId") WHERE "status"='VERIFIED';
CREATE UNIQUE INDEX "PickupOtpChallenge_tenantId_id_key" ON "PickupOtpChallenge"("tenantId","id");
CREATE INDEX "PickupOtpChallenge_tenantId_acceptanceId_status_idx" ON "PickupOtpChallenge"("tenantId","acceptanceId","status");
CREATE INDEX "OtpDeliveryAttempt_tenantId_challengeId_createdAt_idx" ON "OtpDeliveryAttempt"("tenantId","challengeId","createdAt");
CREATE UNIQUE INDEX "AcceptanceSignature_acceptanceId_key" ON "AcceptanceSignature"("acceptanceId");
CREATE UNIQUE INDEX "AcceptanceSignature_storageKey_key" ON "AcceptanceSignature"("storageKey");
CREATE UNIQUE INDEX "AcceptanceSignature_tenantId_acceptanceId_key" ON "AcceptanceSignature"("tenantId","acceptanceId");
ALTER TABLE "PickupAcceptance" ADD FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id"), ADD FOREIGN KEY ("tenantId","pickupId") REFERENCES "ReservationPickup"("tenantId","id") ON DELETE CASCADE;
ALTER TABLE "PickupOtpChallenge" ADD FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id"), ADD FOREIGN KEY ("tenantId","acceptanceId") REFERENCES "PickupAcceptance"("tenantId","id") ON DELETE CASCADE;
ALTER TABLE "OtpDeliveryAttempt" ADD FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id"), ADD FOREIGN KEY ("tenantId","challengeId") REFERENCES "PickupOtpChallenge"("tenantId","id") ON DELETE CASCADE;
ALTER TABLE "AcceptanceSignature" ADD FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id"), ADD FOREIGN KEY ("tenantId","acceptanceId") REFERENCES "PickupAcceptance"("tenantId","id") ON DELETE CASCADE, ADD FOREIGN KEY ("capturedByUserId") REFERENCES "User"("id");
