import {describe,expect,it} from "vitest";
import {getOtpProviderConfig,getOtpProviderReadiness} from "@/server/acceptance/provider-config";
import {ResendEmailOtpProvider} from "@/server/acceptance/resend-provider";
import {ZenviaSmsOtpProvider,ZenviaWhatsAppOtpProvider} from "@/server/acceptance/zenvia-providers";

const base={OTP_PROVIDER_MODE:"production" as const,OTP_PROVIDER_TIMEOUT_MS:8000,ZENVIA_API_TOKEN:"token-placeholder",ZENVIA_API_SECRET:undefined,ZENVIA_WHATSAPP_FROM:"5511000000000",ZENVIA_WHATSAPP_OTP_TEMPLATE_ID:"template-id",ZENVIA_WHATSAPP_TEMPLATE_LOCALE:"pt_BR",ZENVIA_SMS_FROM:"CodexUnit",ZENVIA_WEBHOOK_TOKEN:undefined,RESEND_API_KEY:"resend-placeholder",RESEND_FROM_EMAIL:"otp@notify.example.com",RESEND_FROM_NAME:"Codex Unit",RESEND_WEBHOOK_SECRET:undefined};
const input={destination:"+55 (11) 99999-9999",code:"123456",expiresInSeconds:300,idempotencyKey:"otp/challenge/attempt",metadata:{challengeId:"challenge",deliveryAttemptId:"11111111-1111-4111-8111-111111111111"}};
function response(body:unknown,status=200){return Promise.resolve(new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}}));}
function mockFetch(body:unknown,status=200){const calls:Array<[URL|RequestInfo,RequestInit|undefined]>=[];const fetcher:typeof fetch=async(input,init)=>{calls.push([input,init]);return response(body,status);};return{fetcher,calls};}

describe("production OTP providers",()=>{
  it("sends an approved WhatsApp template through Zenvia API v2",async()=>{const mock=mockFetch({id:"wa-1"});const provider=new ZenviaWhatsAppOtpProvider(base,new (await import("@/server/acceptance/zenvia-providers")).ZenviaClient(base,mock.fetcher));expect((await provider.send(input)).providerMessageId).toBe("wa-1");const[url,init]=mock.calls[0];expect(url).toBe("https://api.zenvia.com/v2/channels/whatsapp/messages");expect((init!.headers as Record<string,string>)["X-API-Token"]).toBe("token-placeholder");expect(JSON.parse(String(init!.body))).toMatchObject({externalId:input.metadata.deliveryAttemptId,from:base.ZENVIA_WHATSAPP_FROM,to:"5511999999999",contents:[{type:"template",templateId:"template-id",fields:{token:"123456",minutes:"5"}}]});});
  it("sends concise SMS and classifies 429 as fallback eligible",async()=>{const ok=mockFetch({id:"sms-1"});const Client=(await import("@/server/acceptance/zenvia-providers")).ZenviaClient;const provider=new ZenviaSmsOtpProvider(base,new Client(base,ok.fetcher));expect((await provider.send(input)).accepted).toBe(true);expect(JSON.parse(String(ok.calls[0][1]!.body))).toMatchObject({from:"CodexUnit",to:"5511999999999",externalId:input.metadata.deliveryAttemptId});const limitedMock=mockFetch({code:"RATE_LIMIT"},429);const limited=new ZenviaSmsOtpProvider(base,new Client(base,limitedMock.fetcher));expect(await limited.send(input)).toMatchObject({accepted:false,retryable:true,fallbackAllowed:true});});
  it("uses Resend HTML/text and mandatory idempotency header",async()=>{const mock=mockFetch({id:"email-1"});const result=await new ResendEmailOtpProvider(base,mock.fetcher).send({...input,destination:"maria@example.com"});expect(result.providerMessageId).toBe("email-1");const[url,init]=mock.calls[0];expect(url).toBe("https://api.resend.com/emails");expect((init!.headers as Record<string,string>)["Idempotency-Key"]).toBe(input.idempotencyKey);expect(JSON.parse(String(init!.body))).toMatchObject({from:"Codex Unit <otp@notify.example.com>",to:["maria@example.com"],subject:"Seu código de confirmação"});});
  it("reports readiness without secrets and blocks unconfigured production",()=>{expect(getOtpProviderReadiness(base).every(item=>item.configured)).toBe(true);expect(()=>getOtpProviderConfig({NODE_ENV:"production",OTP_PROVIDER_MODE:"production"})).toThrow(/requires at least one/);});
});
