import { afterAll, describe, expect, it } from "vitest";
import { prisma } from "@/lib/prisma";
import { completePickup, inspectPickup, refusePickup, startPickup } from "@/server/pickups/pickup-service";
import { approveReservation, createReservation, submitReservationForApproval, transitionReservation } from "@/server/reservations/reservation-service";
const suite=process.env.RUN_DB_INTEGRATION==="1"?describe:describe.skip;
suite("PostgreSQL atomic pickup custody",()=>{
  let reservationId=""; let resourceId="";
  afterAll(async()=>{ if(reservationId){ await prisma.resourceCustodyEvent.deleteMany({where:{reservationId}}); await prisma.reservationPickup.deleteMany({where:{reservationId}}); await prisma.reservation.deleteMany({where:{id:reservationId}}); } if(resourceId) await prisma.resource.update({where:{id:resourceId},data:{operationalStatus:"AVAILABLE"}}); await prisma.$disconnect(); });
  async function fixture(){ const tenant=await prisma.tenant.findUniqueOrThrow({where:{slug:"empresa-demonstracao"}}); const user=await prisma.user.findUniqueOrThrow({where:{email:process.env.SEED_ADMIN_EMAIL??"admin@example.test"}}); const customer=await prisma.customer.findUniqueOrThrow({where:{tenantId_normalizedDocument:{tenantId:tenant.id,normalizedDocument:"DEMO0001"}}}); const unit=await prisma.unit.findUniqueOrThrow({where:{tenantId_code:{tenantId:tenant.id,code:"BASE-SP"}}}); const resource=await prisma.resource.findUniqueOrThrow({where:{tenantId_code:{tenantId:tenant.id,code:"CAB-001"}}}); resourceId=resource.id; const permissions=new Set<string>(["reservations.create","reservations.submit","reservations.approve","reservations.confirm","pickups.start","pickups.inspect","pickups.refuse","pickups.complete"]); const context={tenantId:tenant.id,user:{id:user.id},permissions}; const r=await createReservation(context,{customerId:customer.id,unitId:unit.id,title:"Retirada integrada",startAtLocal:"2026-07-10T10:00",endAtLocal:"2026-07-10T12:00",resourceIds:[resource.id],status:"DRAFT"}); reservationId=r.id; await submitReservationForApproval(context,r.id); await approveReservation(context,r.id); await transitionReservation(context,r.id,"CONFIRMED"); return {context,r}; }
  it("refuses one attempt, allows a new attempt, and completes only once",async()=>{ const {context,r}=await fixture(); const first=await startPickup(context,r.id,{recipientName:"Motorista Um"}); await refusePickup(context,first.id,{reasonCode:"DAMAGE",notes:"Avaria identificada na conferência"}); expect((await prisma.reservation.findUniqueOrThrow({where:{id:r.id}})).status).toBe("READY_FOR_PICKUP"); const second=await startPickup(context,r.id,{recipientName:"Motorista Dois",vehiclePlate:"ABC1D23"}); const items=await prisma.reservationPickupItem.findMany({where:{pickupId:second.id}}); await inspectPickup(context,second.id,{items:items.map(i=>({pickupItemId:i.id,condition:"OK"}))}); const results=await Promise.allSettled([completePickup(context,second.id),completePickup(context,second.id)]); expect(results.filter(x=>x.status==="fulfilled")).toHaveLength(1); expect(await prisma.resourceCustodyEvent.count({where:{pickupId:second.id}})).toBe(items.length); expect((await prisma.reservation.findUniqueOrThrow({where:{id:r.id}})).status).toBe("RELEASED"); expect((await prisma.resource.findUniqueOrThrow({where:{id:resourceId}})).operationalStatus).toBe("IN_USE"); await expect(startPickup(context,r.id,{recipientName:"Terceira tentativa"})).rejects.toMatchObject({code:"CONFLICT"}); });
  it("enforces RBAC and tenant isolation",async()=>{ const tenant=await prisma.tenant.findUniqueOrThrow({where:{slug:"empresa-demonstracao"}}); const user=await prisma.user.findFirstOrThrow(); const noPermission={tenantId:tenant.id,user:{id:user.id},permissions:new Set<string>()}; await expect(completePickup(noPermission,"00000000-0000-4000-8000-000000000001")).rejects.toMatchObject({code:"FORBIDDEN"}); });
});
