import { Button } from "@/components/ui/button";
import { Field, selectClass, textareaClass } from "@/components/operational/operational-ui";

export type ReservationOptions = {
  customers: { id: string; legalName: string }[];
  contracts: { id: string; code: string; customerId: string }[];
  units: { id: string; name: string }[];
  resources: { id: string; code: string; name: string; unitId: string }[];
  timeZone: string;
};

export function ReservationForm({ action, options, reservation, submit = "Salvar reserva", allowInitialStatus = false }: { action: (form: FormData) => Promise<void>; options: ReservationOptions; submit?: string; allowInitialStatus?: boolean; reservation?: { customerId: string; contractId: string | null; unitId: string; title: string; description: string | null; startAtLocal: string; endAtLocal: string; resourceIds: string[] } }) {
  return <form action={action} className="grid gap-5 rounded-xl border bg-background p-5 md:grid-cols-2"><Field label="Cliente" name="customerId" required><select className={selectClass} defaultValue={reservation?.customerId} id="customerId" name="customerId" required><option value="">Selecione</option>{options.customers.map((item) => <option key={item.id} value={item.id}>{item.legalName}</option>)}</select></Field><Field label="Contrato (opcional)" name="contractId"><select className={selectClass} defaultValue={reservation?.contractId ?? ""} id="contractId" name="contractId"><option value="">Sem contrato</option>{options.contracts.map((item) => <option key={item.id} value={item.id}>{item.code}</option>)}</select></Field><Field label="Unidade" name="unitId" required><select className={selectClass} defaultValue={reservation?.unitId} id="unitId" name="unitId" required><option value="">Selecione</option>{options.units.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Finalidade" name="title" required><input className={selectClass} defaultValue={reservation?.title} id="title" name="title" required /></Field><Field label={`Início (${options.timeZone})`} name="startAtLocal" required><input className={selectClass} defaultValue={reservation?.startAtLocal} id="startAtLocal" name="startAtLocal" required type="datetime-local" /></Field><Field label={`Término (${options.timeZone})`} name="endAtLocal" required><input className={selectClass} defaultValue={reservation?.endAtLocal} id="endAtLocal" name="endAtLocal" required type="datetime-local" /></Field><Field label="Recursos" name="resourceIds" required><select className={`${selectClass} min-h-44 py-2`} defaultValue={reservation?.resourceIds ?? []} id="resourceIds" multiple name="resourceIds" required>{options.resources.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select><span className="text-xs font-normal text-muted-foreground">Use Ctrl/Cmd para selecionar mais de um. A disponibilidade temporal será revalidada no servidor.</span></Field><Field label="Descrição" name="description"><textarea className={textareaClass} defaultValue={reservation?.description ?? ""} id="description" name="description" /></Field>{allowInitialStatus && <Field label="Salvar como" name="status"><select className={selectClass} defaultValue="DRAFT" id="status" name="status"><option value="DRAFT">Rascunho — não bloqueia</option><option value="PENDING">Pendente — bloqueia recursos</option></select></Field>}<Button className="self-end md:justify-self-start" type="submit">{submit}</Button></form>;
}
