import { AppHeader } from "@/components/app-header";
import { Button } from "@/components/ui/button";
import { Field, FormCard, Pager, SearchFilters, selectClass, StatusBadge, textareaClass } from "@/components/operational/operational-ui";
import { createContractAction, updateContractAction } from "@/app/operational-actions";
import { hasPermission } from "@/server/authorization/permissions";
import { getContractFormOptions, listContracts } from "@/server/operational/operational-service";
import { requireActiveTenantForPage } from "@/server/tenancy/page-context";

export const dynamic = "force-dynamic";
export const metadata = { title: "Contratos" };

export default async function ContractsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const context = await requireActiveTenantForPage();
  const data = await listContracts(context, await searchParams);
  const canCreate = hasPermission(context.permissions, "contracts.create");
  const canUpdate = hasPermission(context.permissions, "contracts.update");
  const options = canCreate || canUpdate ? await getContractFormOptions(context) : { customers: [], units: [] };
  return <main className="min-h-screen bg-muted"><AppHeader tenantName={context.tenantName} permissions={context.permissions} /><section className="mx-auto grid max-w-7xl gap-6 px-5 py-8 sm:px-8"><header><p className="text-sm font-medium text-primary">Vínculos comerciais</p><h1 className="mt-1 text-3xl font-bold">Contratos</h1><p className="mt-2 text-muted-foreground">Vigência, cliente e unidades aplicáveis com integridade por tenant.</p></header><SearchFilters statusOptions={["DRAFT", "ACTIVE", "SUSPENDED", "EXPIRED", "TERMINATED"]} />{canCreate && <FormCard title="Novo contrato"><ContractForm action={createContractAction} options={options} submit="Criar contrato" /></FormCard>}<div className="grid gap-4">{data.items.length === 0 ? <div className="rounded-xl border border-dashed bg-background p-10 text-center text-muted-foreground">Nenhum contrato encontrado.</div> : data.items.map((contract) => <article className="rounded-xl border bg-background p-5" key={contract.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{contract.code} · {contract.title}</h2><p className="text-sm text-muted-foreground">{contract.customer.legalName}</p></div><StatusBadge>{contract.status}</StatusBadge></div><p className="mt-3 text-sm">{contract.startDate.toLocaleDateString("pt-BR")} → {contract.endDate?.toLocaleDateString("pt-BR") ?? "sem término definido"}</p><p className="mt-1 text-xs text-muted-foreground">{contract.units.map(({ unit }) => unit.name).join(", ") || "Aplicável a todas as unidades"}</p>{canUpdate && <details className="mt-4 border-t pt-4"><summary className="cursor-pointer text-sm font-semibold">Editar</summary><div className="mt-4"><ContractForm action={updateContractAction.bind(null, contract.id)} contract={{ ...contract, unitIds: contract.units.map(({ unitId }) => unitId) }} options={options} submit="Salvar alterações" /></div></details>}</article>)}</div><Pager page={data.page} pageSize={data.pageSize} pathname="/contracts" total={data.total} /></section></main>;
}

function dateValue(value?: Date | null) { return value?.toISOString().slice(0, 10) ?? ""; }
function ContractForm({ action, submit, options, contract }: { action: (form: FormData) => Promise<void>; submit: string; options: { customers: { id: string; legalName: string }[]; units: { id: string; name: string }[] }; contract?: { customerId: string; code: string; title: string; description: string | null; startDate: Date; endDate: Date | null; status: string; unitIds: string[] } }) {
  return <form action={action} className="grid gap-4 md:grid-cols-2"><Field label="Cliente" name="customerId" required><select className={selectClass} defaultValue={contract?.customerId} id="customerId" name="customerId" required><option value="">Selecione</option>{options.customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.legalName}</option>)}</select></Field><Field label="Código" name="code" required><input className={selectClass} defaultValue={contract?.code} id="code" name="code" required /></Field><Field label="Título" name="title" required><input className={selectClass} defaultValue={contract?.title} id="title" name="title" required /></Field><Field label="Status" name="status"><select className={selectClass} defaultValue={contract?.status ?? "DRAFT"} id="status" name="status"><option>DRAFT</option><option>ACTIVE</option><option>SUSPENDED</option><option>EXPIRED</option><option>TERMINATED</option></select></Field><Field label="Início" name="startDate" required><input className={selectClass} defaultValue={dateValue(contract?.startDate)} id="startDate" name="startDate" required type="date" /></Field><Field label="Término" name="endDate"><input className={selectClass} defaultValue={dateValue(contract?.endDate)} id="endDate" name="endDate" type="date" /></Field><Field label="Unidades aplicáveis" name="unitIds"><select className={`${selectClass} min-h-28 py-2`} defaultValue={contract?.unitIds ?? []} id="unitIds" multiple name="unitIds">{options.units.map((unit) => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></Field><Field label="Descrição" name="description"><textarea className={textareaClass} defaultValue={contract?.description ?? ""} id="description" name="description" /></Field><Button className="md:col-span-2 md:justify-self-start" type="submit">{submit}</Button></form>;
}
