import { AppHeader } from "@/components/app-header";
import { Button } from "@/components/ui/button";
import { Field, FormCard, Pager, SearchFilters, selectClass, StatusBadge, textareaClass } from "@/components/operational/operational-ui";
import { createResourceAction, createResourceCategoryAction, updateResourceAction, updateResourceCategoryAction } from "@/app/operational-actions";
import { hasPermission } from "@/server/authorization/permissions";
import { getResourceFormOptions, listResourceCategories, listResources } from "@/server/operational/operational-service";
import { requireActiveTenantForPage } from "@/server/tenancy/page-context";

export const dynamic = "force-dynamic";
export const metadata = { title: "Recursos" };

export default async function ResourcesPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const context = await requireActiveTenantForPage();
  const [data, categories] = await Promise.all([listResources(context, await searchParams), listResourceCategories(context)]);
  const canCreate = hasPermission(context.permissions, "resources.create");
  const canUpdate = hasPermission(context.permissions, "resources.update");
  const canManageCategories = hasPermission(context.permissions, "resource_categories.manage");
  const options = canCreate || canUpdate ? await getResourceFormOptions(context) : { units: [], categories: [] };
  return <main className="min-h-screen bg-muted"><AppHeader tenantName={context.tenantName} permissions={context.permissions} /><section className="mx-auto grid max-w-7xl gap-6 px-5 py-8 sm:px-8"><header><p className="text-sm font-medium text-primary">Ativos locáveis</p><h1 className="mt-1 text-3xl font-bold">Recursos</h1><p className="mt-2 text-muted-foreground">Estado administrativo e operacional. Reservas serão temporais e não alteram este cadastro para “reserved”.</p></header><SearchFilters statusOptions={["ACTIVE", "INACTIVE", "ARCHIVED"]} /><div className="grid gap-4 lg:grid-cols-2">{canCreate && <FormCard title="Novo recurso"><ResourceForm action={createResourceAction} options={options} submit="Criar recurso" /></FormCard>}{canManageCategories && <FormCard title="Nova categoria"><CategoryForm action={createResourceCategoryAction} submit="Criar categoria" /></FormCard>}</div><section><h2 className="text-xl font-semibold">Categorias</h2><div className="mt-3 flex gap-3 overflow-x-auto pb-2">{categories.map((category) => <details className="min-w-56 rounded-xl border bg-background p-4" key={category.id}><summary className="cursor-pointer"><strong>{category.name}</strong><span className="ml-2 text-xs text-muted-foreground">{category.code}</span></summary>{canManageCategories && <div className="mt-4"><CategoryForm action={updateResourceCategoryAction.bind(null, category.id)} category={category} submit="Salvar" /></div>}</details>)}</div></section><div className="grid gap-4 md:grid-cols-2">{data.items.length === 0 ? <div className="rounded-xl border border-dashed bg-background p-10 text-center text-muted-foreground md:col-span-2">Nenhum recurso encontrado.</div> : data.items.map((resource) => <article className="rounded-xl border bg-background p-5" key={resource.id}><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{resource.name}</h2><p className="text-sm text-muted-foreground">{resource.code} · {resource.category.name}</p></div><StatusBadge>{resource.status}</StatusBadge></div><p className="mt-3 text-sm">{resource.unit.name} · Operação: <strong>{resource.operationalStatus}</strong></p><p className="mt-1 text-xs text-muted-foreground">Série: {resource.serialNumber ?? "não informada"}</p>{canUpdate && <details className="mt-4 border-t pt-4"><summary className="cursor-pointer text-sm font-semibold">Editar</summary><div className="mt-4"><ResourceForm action={updateResourceAction.bind(null, resource.id)} options={options} resource={resource} submit="Salvar alterações" /></div></details>}</article>)}</div><Pager page={data.page} pageSize={data.pageSize} pathname="/resources" total={data.total} /></section></main>;
}

function CategoryForm({ action, submit, category }: { action: (form: FormData) => Promise<void>; submit: string; category?: { name: string; code: string; description: string | null; status: string } }) { return <form action={action} className="grid gap-3"><Field label="Nome" name="name" required><input className={selectClass} defaultValue={category?.name} id="name" name="name" required /></Field><Field label="Código" name="code" required><input className={selectClass} defaultValue={category?.code} id="code" name="code" required /></Field><Field label="Status" name="status"><select className={selectClass} defaultValue={category?.status ?? "ACTIVE"} id="status" name="status"><option>ACTIVE</option><option>INACTIVE</option><option>ARCHIVED</option></select></Field><Field label="Descrição" name="description"><textarea className={textareaClass} defaultValue={category?.description ?? ""} id="description" name="description" /></Field><Button type="submit">{submit}</Button></form>; }

function ResourceForm({ action, submit, options, resource }: { action: (form: FormData) => Promise<void>; submit: string; options: { units: { id: string; name: string }[]; categories: { id: string; name: string }[] }; resource?: { unitId: string; categoryId: string; code: string; name: string; description: string | null; serialNumber: string | null; status: string; operationalStatus: string } }) {
  return <form action={action} className="grid gap-4 md:grid-cols-2"><Field label="Unidade" name="unitId" required><select className={selectClass} defaultValue={resource?.unitId} id="unitId" name="unitId" required><option value="">Selecione</option>{options.units.map((unit) => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></Field><Field label="Categoria" name="categoryId" required><select className={selectClass} defaultValue={resource?.categoryId} id="categoryId" name="categoryId" required><option value="">Selecione</option>{options.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><Field label="Código" name="code" required><input className={selectClass} defaultValue={resource?.code} id="code" name="code" required /></Field><Field label="Nome" name="name" required><input className={selectClass} defaultValue={resource?.name} id="name" name="name" required /></Field><Field label="Status administrativo" name="status"><select className={selectClass} defaultValue={resource?.status ?? "ACTIVE"} id="status" name="status"><option>ACTIVE</option><option>INACTIVE</option><option>ARCHIVED</option></select></Field><Field label="Status operacional" name="operationalStatus"><select className={selectClass} defaultValue={resource?.operationalStatus ?? "AVAILABLE"} id="operationalStatus" name="operationalStatus"><option>AVAILABLE</option><option>MAINTENANCE</option><option>UNAVAILABLE</option><option>RETIRED</option></select></Field><Field label="Número de série" name="serialNumber"><input className={selectClass} defaultValue={resource?.serialNumber ?? ""} id="serialNumber" name="serialNumber" /></Field><Field label="Descrição" name="description"><textarea className={textareaClass} defaultValue={resource?.description ?? ""} id="description" name="description" /></Field><Button className="md:col-span-2 md:justify-self-start" type="submit">{submit}</Button></form>;
}
