ALTER TYPE "ReservationStatus" ADD VALUE IF NOT EXISTS 'RETURNED';
ALTER TYPE "EvidenceType" ADD VALUE IF NOT EXISTS 'RETURN_CONDITION';
ALTER TYPE "EvidenceType" ADD VALUE IF NOT EXISTS 'RETURN_DAMAGE';
ALTER TYPE "EvidenceType" ADD VALUE IF NOT EXISTS 'MISSING_COMPONENT';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'RETURNED_TO_TENANT';
