import { notFound } from "next/navigation";
import { AlertTriangle } from "lucide-react";
import { approveReservationAction, cancelReservationAction, rejectReservationAction, reopenReservationAction, setReservationUrgencyAction, submitReservationAction, transitionReservationAction, updateReservationAction } from "@/app/reservation-actions";
import { startPickupAction } from "@/app/pickup-actions";
import { AppHeader } from "@/components/app-header";
import { FormCard, StatusBadge, textareaClass } from "@/components/operational/operational-ui";
import { ReservationForm } from "@/components/reservations/reservation-form";
import { Button } from "@/components/ui/button";
import { hasPermission } from "@/server/authorization/permissions";
import { AppError } from "@/server/errors/app-error";
import { getReservation, getReservationFormOptions } from "@/server/reservations/reservation-service";
import { formatForDateTimeLocal, formatInTimeZone } from "@/server/reservations/timezone";
import { requireActiveTenantForPage } from "@/server/tenancy/page-context";
export const dynamic = "force-dynamic";
export default async function ReservationDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const context = await requireActiveTenantForPage(); let reservation;
  try { reservation = await getReservation(context, (await params).id); } catch (error) { if (error instanceof AppError && error.code === "NOT_FOUND") notFound(); throw error; }
  const canUpdate = hasPermission(context.permissions, "reservations.update") && reservation.status === "DRAFT";
  const options = canUpdate ? await getReservationFormOptions(context) : null;
  const person = (value: { name: string | null; email: string } | null) => value ? value.name ?? value.email : "—";
  return <main className="min-h-screen bg-muted"><AppHeader tenantName={context.tenantName} permissions={context.permissions} /><section className="mx-auto grid max-w-5xl gap-6 px-5 py-8 sm:px-8">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-primary">{reservation.code}</p><h1 className="mt-1 text-3xl font-bold">{reservation.title}</h1><p className="mt-2 text-muted-foreground">{reservation.customer.legalName} · {reservation.unit.name}</p></div><div className="flex gap-2"><StatusBadge>{reservation.status}</StatusBadge>{reservation.isUrgent && <span className="inline-flex items-center gap-1 rounded-full border border-amber-500 px-2 py-1 text-xs font-bold"><AlertTriangle className="size-3" />URGENTE</span>}</div></header>
    <section className="grid gap-4 rounded-xl border bg-background p-5 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Início</p><strong>{formatInTimeZone(reservation.startAt, context.timeZone)}</strong></div><div><p className="text-xs text-muted-foreground">Término</p><strong>{formatInTimeZone(reservation.endAt, context.timeZone)}</strong></div><div><p className="text-xs text-muted-foreground">Solicitante</p><strong>{person(reservation.submittedBy ?? reservation.createdBy)}</strong></div><div><p className="text-xs text-muted-foreground">Aprovador</p><strong>{person(reservation.approvedBy)}</strong></div><div><p className="text-xs text-muted-foreground">Recursos</p><strong>{reservation.items.map(({ resource }) => resource.name).join(", ")}</strong></div>{reservation.isUrgent && <div><p className="text-xs text-muted-foreground">Justificativa da urgência</p><strong>{reservation.urgentReason}</strong></div>}</section>
    <div className="flex flex-wrap gap-3">{reservation.status === "DRAFT" && hasPermission(context.permissions, "reservations.submit") && <form action={submitReservationAction.bind(null, reservation.id)}><Button>Enviar para aprovação</Button></form>}{reservation.status === "PENDING_APPROVAL" && hasPermission(context.permissions, "reservations.approve") && <form action={approveReservationAction.bind(null, reservation.id)}><Button>Aprovar</Button></form>}{reservation.status === "APPROVED" && hasPermission(context.permissions, "reservations.confirm") && <form action={transitionReservationAction.bind(null, reservation.id, "CONFIRMED")}><Button>Confirmar</Button></form>}{reservation.status === "REJECTED" && hasPermission(context.permissions, "reservations.update") && <form action={reopenReservationAction.bind(null, reservation.id)}><Button variant="outline">Reabrir como rascunho</Button></form>}</div>
    {reservation.status === "PENDING_APPROVAL" && hasPermission(context.permissions, "reservations.reject") && <FormCard title="Reprovar reserva"><form action={rejectReservationAction.bind(null, reservation.id)} className="grid gap-3"><textarea className={textareaClass} minLength={3} name="reason" placeholder="Motivo obrigatório" required /><Button variant="outline">Reprovar</Button></form></FormCard>}
    {["CONFIRMED", "READY_FOR_PICKUP"].includes(reservation.status) && hasPermission(context.permissions, "pickups.start") && <FormCard title="Iniciar tentativa de retirada"><form action={startPickupAction.bind(null, reservation.id)} className="grid gap-3 sm:grid-cols-2"><input className="rounded-md border px-3 py-2" minLength={2} name="recipientName" placeholder="Nome de quem retira" required/><input className="rounded-md border px-3 py-2" name="recipientDocument" placeholder="Documento (opcional)"/><input className="rounded-md border px-3 py-2" name="recipientPhone" placeholder="Telefone (opcional)"/><input className="rounded-md border px-3 py-2" name="vehiclePlate" placeholder="Placa (opcional)"/><Button>Iniciar conferência integral</Button></form></FormCard>}
    {hasPermission(context.permissions, "reservations.mark_urgent") && <FormCard title="Urgência"><form action={setReservationUrgencyAction.bind(null, reservation.id, !reservation.isUrgent)} className="grid gap-3">{!reservation.isUrgent && <textarea className={textareaClass} minLength={3} name="reason" placeholder="Justificativa obrigatória" required />}<Button variant="outline">{reservation.isUrgent ? "Remover urgência" : "Marcar como urgente"}</Button></form></FormCard>}
    {reservation.status !== "CANCELLED" && hasPermission(context.permissions, "reservations.cancel") && <FormCard title="Cancelar reserva"><form action={cancelReservationAction.bind(null, reservation.id)} className="grid gap-3"><textarea className={textareaClass} minLength={3} name="reason" placeholder="Motivo obrigatório" required /><Button variant="outline">Cancelar e liberar recursos</Button></form></FormCard>}
    {canUpdate && options && <FormCard title="Editar rascunho"><ReservationForm action={updateReservationAction.bind(null, reservation.id)} options={options} reservation={{ customerId: reservation.customerId, contractId: reservation.contractId, unitId: reservation.unitId, title: reservation.title, description: reservation.description, startAtLocal: formatForDateTimeLocal(reservation.startAt, options.timeZone), endAtLocal: formatForDateTimeLocal(reservation.endAt, options.timeZone), resourceIds: reservation.items.map(({ resourceId }) => resourceId) }} submit="Salvar alterações" /></FormCard>}
    <section className="rounded-xl border bg-background p-5"><h2 className="font-semibold">Histórico de estados e decisões</h2><ol className="mt-4 grid gap-3">{reservation.statusHistory.map((history) => <li className="border-l-2 border-primary pl-3 text-sm" key={history.id}><strong>{history.fromStatus ?? "CRIADA"} → {history.toStatus}</strong><p className="text-muted-foreground">{history.actor.name ?? history.actor.email} · {history.createdAt.toLocaleString("pt-BR")}</p>{history.reason && <p>{history.reason}</p>}</li>)}</ol></section>
  </section></main>;
}
