"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { checkConnectivity } from "@/lib/offline/connectivity";
import { offlineStore, type OfflineAttachment, type OfflineOperation } from "@/lib/offline/offline-store";
import { syncNow } from "@/lib/offline/sync-engine";

const labels: Record<string, string> = { PENDING: "Pendente", SYNCING: "Sincronizando", SYNCED: "Confirmada", FAILED_RETRYABLE: "Nova tentativa agendada", FAILED_PERMANENT: "Rejeitada", CONFLICT: "Conflito", AUTH_REQUIRED: "Aguardando autenticação" };
export function SyncCenter({ tenantId, userId }: { tenantId: string; userId: string }) {
  const [rows, setRows] = useState<OfflineOperation[]>([]), [attachmentStates, setAttachmentStates] = useState<Record<string, Pick<OfflineAttachment, "id" | "purpose" | "status" | "attemptCount" | "lastErrorCode" | "serverAcceptanceId">[]>>({}), [online, setOnline] = useState(false), [running, setRunning] = useState(false), [message, setMessage] = useState("");
  const refresh = useCallback(async () => { setOnline(await checkConnectivity()); try { const operations = await offlineStore.getPendingOperations(tenantId, userId); setRows(operations); const states: Record<string, Pick<OfflineAttachment, "id" | "purpose" | "status" | "attemptCount" | "lastErrorCode" | "serverAcceptanceId">[]> = {}; for (const row of operations) states[row.id] = (await offlineStore.getAttachments(row.id, tenantId, userId)).map(({ id, purpose, status, attemptCount, lastErrorCode, serverAcceptanceId }) => ({ id, purpose, status, attemptCount, lastErrorCode, serverAcceptanceId })); setAttachmentStates(states); } catch { setMessage("Não foi possível ler as pendências deste dispositivo."); } }, [tenantId, userId]);
  useEffect(() => { const timer = window.setTimeout(() => void refresh(), 0); return () => window.clearTimeout(timer); }, [refresh]);
  async function synchronize() { setRunning(true); try { const result = await syncNow(tenantId, userId); setMessage(result.authRequired ? "Entre novamente para retomar; as pendências permanecem no dispositivo." : `${result.synced} operação(ões) confirmada(s), ${result.conflicts} conflito(s), ${result.failed} falha(s).`); } finally { setRunning(false); await refresh(); } }
  async function discard(row: OfflineOperation) {
    if (!window.confirm("Descartar esta operação local rejeitada? Esta ação não pode ser desfeita.")) return;
    await offlineStore.discardRejected(row.id, tenantId, userId); await refresh();
  }
  return <div className="grid gap-4">
    <div className="surface-card flex flex-wrap items-center justify-between gap-3"><div><strong>{online ? "Conectado" : "Sem conexão"}</strong><p className="text-sm text-muted-foreground">Somente a confirmação do servidor conclui uma operação.</p></div><button onClick={synchronize} disabled={!online || running} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{running ? "Sincronizando…" : "Sincronizar agora"}</button></div>
    {message&&<p role="status" className="text-sm">{message}</p>}
    {rows.length===0?<div className="surface-card">Nenhuma pendência local para esta conta e empresa.</div>:rows.map(row=><article className="surface-card" key={row.id}>
      <div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{row.operationType === "PICKUP_ATTACHMENTS" ? "Retirada — evidências e aceite" : row.operationType === "MAINTENANCE_ADD_DIAGNOSIS" ? "Diagnóstico" : row.operationType === "MAINTENANCE_ADD_EVIDENCE" ? "Evidência" : "Intervenção"}</strong><p className="text-sm text-muted-foreground">{row.payload.description}</p><p className="mt-2 text-xs text-muted-foreground">Registrado em {new Date(row.createdAt).toLocaleString("pt-BR")} · {row.attemptCount} tentativa(s) · {attachmentStates[row.id]?.filter(a=>a.status!=="SERVER_CONFIRMED").length ?? 0} anexo(s) pendente(s)</p>{row.domainConfirmed&&<p className="text-xs text-muted-foreground">Operação preparada no servidor; aguardando anexos.</p>}{row.lastErrorCode&&<p className="text-xs text-destructive">Último erro: {row.lastErrorCode}</p>}</div><span className="rounded-full bg-muted px-3 py-1 text-xs font-semibold">{labels[row.status]}</span></div>
      {(attachmentStates[row.id]?.length??0)>0&&<div className="mt-3 grid gap-1 border-t pt-3 text-xs">{row.operationType === "PICKUP_ATTACHMENTS" && <><p>Evidências: {attachmentStates[row.id].filter(a=>a.purpose==="PICKUP_EVIDENCE"&&a.status==="SERVER_CONFIRMED").length}/{attachmentStates[row.id].filter(a=>a.purpose==="PICKUP_EVIDENCE").length} confirmadas</p><p>Assinatura: {attachmentStates[row.id].find(a=>a.purpose==="PICKUP_SIGNATURE")?.status === "SERVER_CONFIRMED" ? "confirmada" : attachmentStates[row.id].some(a=>a.purpose==="PICKUP_SIGNATURE") ? "salva no dispositivo / aguardando servidor" : "não capturada"}</p><p>Aceite: {attachmentStates[row.id].some(a=>Boolean(a.serverAcceptanceId)) ? "verificado no servidor" : "pendente"}</p><p>Conclusão: ainda não enviada. Resource e custódia inalterados.</p></>}{attachmentStates[row.id].map(a=><p key={a.id}>{a.purpose==="PICKUP_SIGNATURE"?"Assinatura":"Evidência"} {a.id.slice(0,8)} · {a.status} · {a.attemptCount} tentativa(s) {a.lastErrorCode&&`· ${a.lastErrorCode}`}</p>)}</div>}
      {row.status==="CONFLICT"&&<p className="mt-3 text-sm text-amber-800">O registro mudou no servidor. <Link href={row.aggregateType==="ReservationPickup"?`/pickups/${row.aggregateId}`:`/maintenance/${row.aggregateId}`} className="underline">Revise o estado atual</Link> antes de registrar novamente. Não houve mesclagem automática.</p>}
      {row.status==="AUTH_REQUIRED"&&<p className="mt-3 text-sm">Entre novamente para retomar a sincronização; nada foi descartado.</p>}
      {row.status==="FAILED_PERMANENT"&&<p className="mt-3 text-sm text-destructive">O servidor rejeitou a operação ({row.lastErrorCode}). Revise permissões e dados.</p>}
      {["CONFLICT","FAILED_PERMANENT"].includes(row.status)&&<button onClick={() => discard(row)} className="mt-3 text-sm font-semibold text-destructive underline">Descartar operação local</button>}
    </article>)}
  </div>;
}
