import { completePickupAction, inspectPickupAction, refusePickupAction } from "@/app/pickup-actions";
import { AppHeader } from "@/components/app-header";
import { selectClass, textareaClass } from "@/components/operational/operational-ui";
import { Button } from "@/components/ui/button";
import { hasPermission } from "@/server/authorization/permissions";
import { getPickup } from "@/server/pickups/pickup-service";
import { requireActiveTenantForPage } from "@/server/tenancy/page-context";
export const dynamic="force-dynamic";
export default async function PickupPage({params}:{params:Promise<{id:string}>}) { const context=await requireActiveTenantForPage(); const p=await getPickup(context,(await params).id); const ids=p.items.map(i=>i.id); return <main className="min-h-screen bg-muted"><AppHeader tenantName={context.tenantName} permissions={context.permissions}/><section className="mx-auto grid max-w-4xl gap-5 px-5 py-8"><header><p className="text-sm text-primary">{p.reservation.code}</p><h1 className="text-3xl font-bold">Conferência de retirada</h1><p>{p.recipientName} · {p.status}</p></header><form action={inspectPickupAction.bind(null,p.id,ids)} className="grid gap-3">{p.items.map(i=><article className="grid gap-3 rounded-xl border bg-background p-4" key={i.id}><strong>{i.resource.code} · {i.resource.name}</strong><select className={selectClass} defaultValue={i.condition} name={`condition-${i.id}`}><option>OK</option><option>DAMAGED</option><option>DIVERGENT</option><option>OTHER</option></select><textarea className={textareaClass} defaultValue={i.notes??""} name={`notes-${i.id}`} placeholder="Observação obrigatória para irregularidade"/></article>)}{p.status==="IN_PROGRESS"&&hasPermission(context.permissions,"pickups.inspect")&&<Button>Salvar conferência integral</Button>}</form>{p.status==="IN_PROGRESS"&&<div className="grid gap-4 sm:grid-cols-2">{hasPermission(context.permissions,"pickups.complete")&&<form action={completePickupAction.bind(null,p.id)} className="rounded-xl border bg-background p-4"><p className="mb-3 text-sm">Confirma a saída integral de todos os recursos?</p><Button>Concluir retirada</Button></form>}{hasPermission(context.permissions,"pickups.refuse")&&<form action={refusePickupAction.bind(null,p.id)} className="grid gap-3 rounded-xl border bg-background p-4"><select className={selectClass} name="reasonCode" required><option value="">Motivo da recusa</option><option>DAMAGE</option><option>RESOURCE_MISMATCH</option><option>DOCUMENT_MISMATCH</option><option>RECIPIENT_MISMATCH</option><option>RESERVATION_INVALID</option><option>OTHER</option></select><textarea className={textareaClass} minLength={3} name="notes" required/><Button variant="outline">Recusar tentativa inteira</Button></form>}</div>}</section></main>; }
