import Link from "next/link";
import { AlertTriangle } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { selectClass } from "@/components/operational/operational-ui";
import { Button } from "@/components/ui/button";
import { listPickupQueue } from "@/server/pickups/pickup-service";
import { formatInTimeZone } from "@/server/reservations/timezone";
import { requireActiveTenantForPage } from "@/server/tenancy/page-context";
export const dynamic = "force-dynamic";
export default async function PickupsPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) { const context=await requireActiveTenantForPage(); const query=await searchParams; const rows=await listPickupQueue(context,query); return <main className="min-h-screen bg-muted"><AppHeader tenantName={context.tenantName} permissions={context.permissions}/><section className="mx-auto grid max-w-6xl gap-5 px-5 py-8"><header><p className="text-sm font-medium text-primary">Operação de saída</p><h1 className="text-3xl font-bold">Fila da portaria</h1></header><form className="grid gap-3 rounded-xl border bg-background p-4 sm:grid-cols-4"><input className={selectClass} defaultValue={query.search} name="search" placeholder="Reserva ou cliente"/><select className={selectClass} defaultValue={query.status} name="status"><option value="">Aguardando e histórico</option><option value="refused">Recusadas</option><option value="completed">Concluídas</option></select><select className={selectClass} defaultValue={query.urgent} name="urgent"><option value="">Todas</option><option value="true">Urgentes</option></select><Button>Filtrar</Button></form><div className="grid gap-3">{rows.map(r=><article className="rounded-xl border bg-background p-5" key={r.id}><div className="flex flex-wrap justify-between gap-3"><div><strong>{r.code} · {r.customer.legalName}</strong><p className="text-sm text-muted-foreground">{r.unit.name} · {r._count.items} recurso(s) · {formatInTimeZone(r.startAt,context.timeZone)}</p>{r.isUrgent&&<span className="inline-flex items-center gap-1 text-xs font-bold"><AlertTriangle className="size-3"/>URGENTE</span>}</div><div className="flex gap-2">{r.pickups[0]&&<Button asChild variant="outline"><Link href={`/pickups/${r.pickups[0].id}`}>Ver tentativa</Link></Button>}<Button asChild><Link href={`/reservations/${r.id}`}>Abrir reserva</Link></Button></div></div></article>)}</div></section></main>; }
