import { randomUUID } from "node:crypto";
import { Prisma, type MaintenancePriority, type MaintenanceSource } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/server/authorization/permissions";
import { AppError } from "@/server/errors/app-error";
import type { OperationalContext } from "@/server/operational/service-helpers";
import { ACTIVE_MAINTENANCE_STATUSES, assertMaintenanceTransition } from "./maintenance-state-machine";
import { activitySchema,cancelSchema,createMaintenanceSchema,descriptionSchema,maintenanceListSchema,releaseSchema,transitionMaintenanceSchema } from "./maintenance-validation";

type Tx=Prisma.TransactionClient;
const conflict=(message="A ordem foi alterada por outra operação.")=>new AppError("CONFLICT",message);
const code=()=>`OS-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${randomUUID().slice(0,8).toUpperCase()}`;
const audit=(context:OperationalContext,action:string,id:string,metadata?:Prisma.InputJsonValue)=>({scope:"TENANT" as const,tenantId:context.tenantId,actorUserId:context.user.id,action,entityType:"MaintenanceOrder",entityId:id,metadata});
function mapError(error:unknown):never{if(error instanceof AppError)throw error;if(error instanceof Prisma.PrismaClientKnownRequestError&&["P2002","P2034"].includes(error.code))throw conflict("Já existe uma ordem ativa para este recurso.");throw error;}

export async function createOrderInTransaction(tx:Tx,context:OperationalContext,input:{resourceId:string;sourceType:MaintenanceSource;sourceReturnId?:string;sourceReturnItemId?:string;title:string;description:string;priority?:MaintenancePriority}){
  const resource=await tx.resource.findFirst({where:{id:input.resourceId,tenantId:context.tenantId},select:{id:true,operationalStatus:true}});
  if(!resource)throw new AppError("NOT_FOUND","Recurso não encontrado.");
  if(resource.operationalStatus==="IN_USE")throw conflict("O recurso deve ser devolvido antes da manutenção.");
  const order=await tx.maintenanceOrder.create({data:{tenantId:context.tenantId,openedByUserId:context.user.id,code:code(),priority:"NORMAL",...input}});
  if(resource.operationalStatus==="AVAILABLE")await tx.resource.update({where:{id:resource.id},data:{operationalStatus:"MAINTENANCE"}});
  await tx.maintenanceStatusHistory.create({data:{tenantId:context.tenantId,maintenanceOrderId:order.id,toStatus:"OPEN",actorUserId:context.user.id}});
  await tx.auditLog.create({data:audit(context,"maintenance.created",order.id,{resourceId:input.resourceId,sourceType:input.sourceType})});
  await tx.auditLog.create({data:{...audit(context,"resource.entered_maintenance",input.resourceId,{maintenanceOrderId:order.id}),entityType:"Resource"}});
  const impacted=await tx.reservation.findMany({where:{tenantId:context.tenantId,endAt:{gte:new Date()},status:{in:["PENDING_APPROVAL","APPROVED","CONFIRMED","READY_FOR_PICKUP"]},items:{some:{resourceId:input.resourceId}}},select:{id:true,code:true,startAt:true},orderBy:{startAt:"asc"}});
  return {order,impactedReservations:impacted};
}
export async function createMaintenanceOrder(context:OperationalContext,raw:unknown){requirePermission(context.permissions,"maintenance.create");const input=createMaintenanceSchema.parse(raw);try{return await prisma.$transaction(tx=>createOrderInTransaction(tx,context,input),{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}catch(error){mapError(error);}}
export async function transitionMaintenance(context:OperationalContext,id:string,raw:unknown){requirePermission(context.permissions,"maintenance.update");const input=transitionMaintenanceSchema.parse(raw);try{return await prisma.$transaction(async tx=>{const order=await tx.maintenanceOrder.findFirst({where:{id,tenantId:context.tenantId}});if(!order)throw new AppError("NOT_FOUND","Ordem não encontrada.");assertMaintenanceTransition(order.status,input.toStatus);const now=new Date(),changed=await tx.maintenanceOrder.updateMany({where:{id,tenantId:context.tenantId,status:order.status},data:{status:input.toStatus,...(input.toStatus==="DIAGNOSING"?{diagnosedAt:now}:{}),...(input.toStatus==="IN_PROGRESS"?{startedAt:order.startedAt??now}:{}),...(input.toStatus==="COMPLETED"?{completedAt:now}:{})}});if(changed.count!==1)throw conflict();await tx.maintenanceStatusHistory.create({data:{tenantId:context.tenantId,maintenanceOrderId:id,fromStatus:order.status,toStatus:input.toStatus,actorUserId:context.user.id,reason:input.reason}});await tx.auditLog.create({data:audit(context,`maintenance.${input.toStatus.toLowerCase()}`,id)});return input.toStatus;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}catch(error){mapError(error);}}
export async function addDiagnosis(context:OperationalContext,id:string,raw:unknown){requirePermission(context.permissions,"maintenance.diagnose");const input=descriptionSchema.parse(raw);const order=await prisma.maintenanceOrder.findFirst({where:{id,tenantId:context.tenantId,status:{in:ACTIVE_MAINTENANCE_STATUSES}}});if(!order)throw new AppError("NOT_FOUND","Ordem não encontrada.");const result=await prisma.maintenanceDiagnosis.create({data:{tenantId:context.tenantId,maintenanceOrderId:id,description:input.description,diagnosedByUserId:context.user.id}});await prisma.auditLog.create({data:audit(context,"maintenance.diagnosis_added",id)});return result;}
export async function addMaintenanceActivity(context:OperationalContext,id:string,raw:unknown){requirePermission(context.permissions,"maintenance.perform");const input=activitySchema.parse(raw);const order=await prisma.maintenanceOrder.findFirst({where:{id,tenantId:context.tenantId,status:{in:ACTIVE_MAINTENANCE_STATUSES}}});if(!order)throw new AppError("NOT_FOUND","Ordem não encontrada.");const result=await prisma.maintenanceActivity.create({data:{tenantId:context.tenantId,maintenanceOrderId:id,performedByUserId:context.user.id,...input}});await prisma.auditLog.create({data:audit(context,"maintenance.activity_added",id,{type:input.type})});return result;}
export async function releaseMaintenanceOrder(context:OperationalContext,id:string,raw:unknown){requirePermission(context.permissions,"maintenance.release");const input=releaseSchema.parse(raw);try{return await prisma.$transaction(async tx=>{const order=await tx.maintenanceOrder.findFirst({where:{id,tenantId:context.tenantId},include:{resource:true,evidence:true}});if(!order||order.status!=="COMPLETED")throw conflict("Somente uma ordem concluída pode ser liberada.");if(!["MAINTENANCE","UNAVAILABLE"].includes(order.resource.operationalStatus))throw conflict("O recurso não está bloqueado operacionalmente.");const now=new Date(),changed=await tx.maintenanceOrder.updateMany({where:{id,tenantId:context.tenantId,status:"COMPLETED"},data:{status:"RELEASED",releasedAt:now,releasedByUserId:context.user.id,releaseNotes:input.releaseNotes}});if(changed.count!==1)throw conflict();await tx.resource.update({where:{id:order.resourceId},data:{operationalStatus:"AVAILABLE"}});await tx.maintenanceStatusHistory.create({data:{tenantId:context.tenantId,maintenanceOrderId:id,fromStatus:"COMPLETED",toStatus:"RELEASED",actorUserId:context.user.id,reason:input.releaseNotes}});await tx.auditLog.create({data:audit(context,"maintenance.released",id)});await tx.auditLog.create({data:{...audit(context,"resource.released_from_maintenance",order.resourceId,{maintenanceOrderId:id}),entityType:"Resource"}});return true;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}catch(error){mapError(error);}}
export async function cancelMaintenanceOrder(context:OperationalContext,id:string,raw:unknown){requirePermission(context.permissions,"maintenance.cancel");const input=cancelSchema.parse(raw);try{return await prisma.$transaction(async tx=>{const order=await tx.maintenanceOrder.findFirst({where:{id,tenantId:context.tenantId,status:{in:["OPEN","DIAGNOSING","WAITING"]}}});if(!order)throw conflict("Esta ordem não pode ser cancelada.");const changed=await tx.maintenanceOrder.updateMany({where:{id,status:order.status},data:{status:"CANCELLED",cancellationReason:input.cancellationReason}});if(changed.count!==1)throw conflict();await tx.resource.update({where:{id:order.resourceId},data:{operationalStatus:input.resultingOperationalStatus}});await tx.maintenanceStatusHistory.create({data:{tenantId:context.tenantId,maintenanceOrderId:id,fromStatus:order.status,toStatus:"CANCELLED",actorUserId:context.user.id,reason:input.cancellationReason}});await tx.auditLog.create({data:audit(context,"maintenance.cancelled",id,{resultingOperationalStatus:input.resultingOperationalStatus})});return true;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}catch(error){mapError(error);}}
export async function listMaintenanceOrders(context:OperationalContext,raw:unknown={}){requirePermission(context.permissions,"maintenance.view");const q=maintenanceListSchema.parse(raw),take=20;const where:Prisma.MaintenanceOrderWhereInput={tenantId:context.tenantId,...(q.status?{status:q.status}:{}),...(q.priority?{priority:q.priority}:{}),...(q.search?{OR:[{code:{contains:q.search,mode:"insensitive"}},{title:{contains:q.search,mode:"insensitive"}},{resource:{name:{contains:q.search,mode:"insensitive"}}}]}:{})};const [rows,total]=await Promise.all([prisma.maintenanceOrder.findMany({where,include:{resource:{include:{category:true,unit:true}}},orderBy:{openedAt:"desc"},skip:(q.page-1)*take,take}),prisma.maintenanceOrder.count({where})]);return{rows,total,page:q.page,pageSize:take};}
export async function getMaintenanceOrder(context:OperationalContext,id:string){requirePermission(context.permissions,"maintenance.view");const order=await prisma.maintenanceOrder.findFirst({where:{id,tenantId:context.tenantId},include:{resource:{include:{category:true,unit:true}},sourceReturn:true,diagnoses:{orderBy:{diagnosedAt:"desc"},include:{diagnosedBy:{select:{name:true,email:true}}}},activities:{orderBy:{occurredAt:"desc"},include:{performedBy:{select:{name:true,email:true}}}},evidence:true,statusHistory:{orderBy:{createdAt:"desc"},include:{actor:{select:{name:true,email:true}}}}}});if(!order)throw new AppError("NOT_FOUND","Ordem não encontrada.");const upcoming=await prisma.reservation.findMany({where:{tenantId:context.tenantId,endAt:{gte:new Date()},status:{in:["PENDING_APPROVAL","APPROVED","CONFIRMED","READY_FOR_PICKUP"]},items:{some:{resourceId:order.resourceId}}},select:{id:true,code:true,title:true,startAt:true},orderBy:{startAt:"asc"},take:10});return{order,upcoming};}
