import { createHash, createHmac, randomInt, randomUUID, timingSafeEqual } from "node:crypto";
import { Prisma, type AcceptanceMethod, type OtpChannel } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/server/authorization/permissions";
import { AppError } from "@/server/errors/app-error";
import type { OperationalContext } from "@/server/operational/service-helpers";
import { localStorageProvider } from "@/server/storage/local-storage-provider";
import type { StorageProvider } from "@/server/storage/storage-provider";
import { buildPickupTerms } from "./acceptance-terms";
import type { OtpDeliveryProvider } from "./otp-provider";
export const OTP_EXPIRES_SECONDS=300, OTP_MAX_ATTEMPTS=5, OTP_COOLDOWN_SECONDS=30;
const err=(code:"NOT_FOUND"|"CONFLICT"|"VALIDATION_ERROR",message:string)=>new AppError(code,message);
function secret(){const value=process.env.OTP_HMAC_SECRET;if(!value||value.length<32)throw new Error("OTP_HMAC_SECRET must contain at least 32 characters");return value;}
function otpHash(challengeId:string,code:string){return createHmac("sha256",secret()).update(`${challengeId}:${code}`).digest("hex");}
function safeEqual(a:string,b:string){const x=Buffer.from(a,"hex"),y=Buffer.from(b,"hex");return x.length===y.length&&timingSafeEqual(x,y);}
function mask(value:string){return value.includes("@")?value.replace(/^(.).+(@.+)$/,"$1***$2"):value.replace(/.(?=.{4})/g,"*");}
async function pickupForAcceptance(tenantId:string,pickupId:string){const pickup=await prisma.reservationPickup.findFirst({where:{id:pickupId,tenantId,status:"IN_PROGRESS"},include:{reservation:true,items:{include:{resource:true}}}});if(!pickup)throw err("NOT_FOUND","Retirada não encontrada.");const terms=buildPickupTerms({reservationCode:pickup.reservation.code,recipientName:pickup.recipientName,resources:pickup.items.map(i=>`${i.resource.code} ${i.resource.name}`),conditions:pickup.items.map(i=>i.condition)});return{pickup,terms};}
const audit=(c:OperationalContext,action:string,id:string,metadata?:Prisma.InputJsonValue)=>({scope:"TENANT" as const,tenantId:c.tenantId,actorUserId:c.user.id,action,entityType:"PickupAcceptance",entityId:id,metadata});

export async function requestAcceptanceOtp(context:OperationalContext,pickupId:string,input:{phone?:string;email?:string},providers:OtpDeliveryProvider[]){requirePermission(context.permissions,"pickups.acceptance.request_otp");const {pickup,terms}=await pickupForAcceptance(context.tenantId,pickupId);const recent=await prisma.pickupOtpChallenge.findFirst({where:{tenantId:context.tenantId,acceptance:{pickupId},sentAt:{gt:new Date(Date.now()-OTP_COOLDOWN_SECONDS*1000)}}});if(recent)throw err("CONFLICT","Aguarde antes de solicitar outro código.");const choices:[OtpChannel,string|null|undefined][]=[["WHATSAPP",input.phone??pickup.recipientPhone],["SMS",input.phone??pickup.recipientPhone],["EMAIL",input.email]];let lastError="NO_DESTINATION";for(const[channel,destination]of choices){if(!destination)continue;const provider=providers.find(p=>p.channel===channel);if(!provider)continue;const challengeId=randomUUID(),code=randomInt(0,1_000_000).toString().padStart(6,"0");const result=await provider.send({destination,code,expiresInSeconds:OTP_EXPIRES_SECONDS});if(!result.accepted&&!result.retryable)throw err("CONFLICT","Não foi possível enviar o código.");if(!result.accepted){lastError=result.errorCode??"DELIVERY_FAILED";continue;}const method=(`OTP_${channel}`)as AcceptanceMethod;return prisma.$transaction(async tx=>{await tx.pickupOtpChallenge.updateMany({where:{tenantId:context.tenantId,acceptance:{pickupId},status:"PENDING"},data:{status:"INVALIDATED",invalidatedAt:new Date()}});await tx.pickupAcceptance.updateMany({where:{tenantId:context.tenantId,pickupId,status:"PENDING"},data:{status:"CANCELLED"}});const acceptance=await tx.pickupAcceptance.create({data:{tenantId:context.tenantId,pickupId,method,signerName:pickup.recipientName,signerDocument:pickup.recipientDocument,signerPhone:pickup.recipientPhone,signerEmail:input.email,termsVersion:terms.version,termsHash:terms.hash,termsSnapshot:terms.snapshot,expiresAt:new Date(Date.now()+OTP_EXPIRES_SECONDS*1000)}});const challenge=await tx.pickupOtpChallenge.create({data:{id:challengeId,tenantId:context.tenantId,acceptanceId:acceptance.id,channel,destinationMasked:mask(destination),destinationHash:createHash("sha256").update(destination).digest("hex"),codeHash:otpHash(challengeId,code),maxAttempts:OTP_MAX_ATTEMPTS,expiresAt:new Date(Date.now()+OTP_EXPIRES_SECONDS*1000)}});await tx.otpDeliveryAttempt.create({data:{tenantId:context.tenantId,challengeId:challenge.id,channel,provider:provider.name,status:"SENT",providerMessageId:result.providerMessageId}});await tx.auditLog.create({data:audit(context,"acceptance.otp_sent",acceptance.id,{channel,provider:provider.name,destination:mask(destination)})});return{acceptance,challenge,channel};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}throw err("CONFLICT",`Nenhum canal disponível (${lastError}).`);}

export async function verifyAcceptanceOtp(context:OperationalContext,challengeId:string,code:string){requirePermission(context.permissions,"pickups.acceptance.verify");const current=await prisma.pickupOtpChallenge.findFirst({where:{id:challengeId,tenantId:context.tenantId}});if(!current||current.status!=="PENDING"||current.expiresAt<=new Date()||current.attempts>=current.maxAttempts)throw err("CONFLICT","Código inválido ou expirado.");if(!safeEqual(current.codeHash,otpHash(current.id,code))){const attempts=current.attempts+1;await prisma.pickupOtpChallenge.updateMany({where:{id:current.id,tenantId:context.tenantId,status:"PENDING",attempts:current.attempts},data:{attempts,status:attempts>=current.maxAttempts?"BLOCKED":"PENDING"}});throw err("VALIDATION_ERROR","Código inválido ou expirado.");}try{return await prisma.$transaction(async tx=>{const challenge=await tx.pickupOtpChallenge.findFirst({where:{id:challengeId,tenantId:context.tenantId},include:{acceptance:true}});if(!challenge)throw err("NOT_FOUND","Código inválido ou expirado.");if(challenge.status!=="PENDING"||challenge.expiresAt<=new Date()||challenge.attempts>=challenge.maxAttempts)throw err("CONFLICT","Código inválido ou expirado.");if(!safeEqual(challenge.codeHash,otpHash(challenge.id,code))){const attempts=challenge.attempts+1;await tx.pickupOtpChallenge.updateMany({where:{id:challenge.id,status:"PENDING",attempts:challenge.attempts},data:{attempts,status:attempts>=challenge.maxAttempts?"BLOCKED":"PENDING"}});throw err("VALIDATION_ERROR","Código inválido ou expirado.");}const used=await tx.pickupOtpChallenge.updateMany({where:{id:challenge.id,tenantId:context.tenantId,status:"PENDING",attempts:challenge.attempts},data:{status:"VERIFIED",verifiedAt:new Date()}});if(used.count!==1)throw err("CONFLICT","Código inválido ou expirado.");const verified=await tx.pickupAcceptance.updateMany({where:{id:challenge.acceptanceId,tenantId:context.tenantId,status:"PENDING",pickup:{status:"IN_PROGRESS"}},data:{status:"VERIFIED",acceptedAt:new Date()}});if(verified.count!==1)throw err("CONFLICT","Esta retirada já possui aceite final.");await tx.pickupOtpChallenge.updateMany({where:{tenantId:context.tenantId,acceptanceId:challenge.acceptanceId,status:"PENDING"},data:{status:"INVALIDATED",invalidatedAt:new Date()}});await tx.auditLog.create({data:audit(context,"acceptance.otp_verified",challenge.acceptanceId,{channel:challenge.channel})});return tx.pickupAcceptance.findUniqueOrThrow({where:{id:challenge.acceptanceId}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}catch(e){if(e instanceof AppError)throw e;if(e instanceof Prisma.PrismaClientKnownRequestError&&["P2002","P2034"].includes(e.code))throw err("CONFLICT","Esta retirada já possui aceite final.");throw e;}}

export async function captureDrawnSignature(context:OperationalContext,pickupId:string,input:{content:Uint8Array;width:number;height:number},storage:StorageProvider=localStorageProvider){requirePermission(context.permissions,"pickups.acceptance.capture_signature");const {pickup,terms}=await pickupForAcceptance(context.tenantId,pickupId);if(input.content.length<64||input.content.length>2_000_000||input.width<100||input.height<50||![0x89,0x50,0x4e,0x47].every((b,i)=>input.content[i]===b))throw err("VALIDATION_ERROR","Assinatura vazia ou inválida.");const key=`${context.tenantId}/acceptance/${randomUUID()}.png`,checksum=createHash("sha256").update(input.content).digest("hex");await storage.put(key,input.content,"image/png");try{return await prisma.$transaction(async tx=>{const acceptance=await tx.pickupAcceptance.create({data:{tenantId:context.tenantId,pickupId,method:"DRAWN_SIGNATURE",status:"VERIFIED",signerName:pickup.recipientName,signerDocument:pickup.recipientDocument,signerPhone:pickup.recipientPhone,termsVersion:terms.version,termsHash:terms.hash,termsSnapshot:terms.snapshot,acceptedAt:new Date()}});await tx.acceptanceSignature.create({data:{tenantId:context.tenantId,acceptanceId:acceptance.id,storageKey:key,mimeType:"image/png",size:input.content.length,checksum,width:input.width,height:input.height,capturedByUserId:context.user.id}});await tx.auditLog.create({data:audit(context,"acceptance.signature_captured",acceptance.id,{checksum})});return acceptance;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}catch(e){await storage.delete(key);if(e instanceof Prisma.PrismaClientKnownRequestError&&["P2002","P2034"].includes(e.code))throw err("CONFLICT","Esta retirada já possui aceite final.");throw e;}}
export async function hasValidPickupAcceptance(tx:Prisma.TransactionClient,tenantId:string,pickupId:string){return Boolean(await tx.pickupAcceptance.findFirst({where:{tenantId,pickupId,status:"VERIFIED",acceptedAt:{not:null}},select:{id:true}}));}
