import {createHmac,timingSafeEqual} from "node:crypto";
import {Prisma,type OtpDeliveryStatus} from "@prisma/client";
import {prisma} from "@/lib/prisma";

const rank:Record<OtpDeliveryStatus,number>={PENDING:0,SENT:1,ACCEPTED:1,DELAYED:2,DELIVERED:4,FAILED:3,BOUNCED:4,UNDELIVERED:4};
const terminal=new Set<OtpDeliveryStatus>(["DELIVERED","BOUNCED","UNDELIVERED"]);
function safeHeader(actual:string|null,expected:string|undefined){if(!actual||!expected)return false;const a=Buffer.from(actual),b=Buffer.from(expected);return a.length===b.length&&timingSafeEqual(a,b);}
async function apply(provider:string,eventId:string,eventType:string,messageId:string|undefined,externalId:string|undefined,status:OtpDeliveryStatus,eventAt:Date){
  try{return await prisma.$transaction(async tx=>{await tx.otpWebhookEvent.create({data:{provider,eventId,eventType}});const uuid=externalId&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(externalId)?externalId:undefined;const attempt=await tx.otpDeliveryAttempt.findFirst({where:{provider,...(uuid||messageId?{OR:[...(uuid?[{id:uuid}]:[]),...(messageId?[{providerMessageId:messageId}]:[])]}:{id:"00000000-0000-0000-0000-000000000000"})}});if(!attempt)return{matched:false,duplicate:false};if(attempt.lastEventAt&&attempt.lastEventAt>eventAt)return{matched:true,duplicate:false};if(terminal.has(attempt.status)&&rank[status]<=rank[attempt.status])return{matched:true,duplicate:false};await tx.otpDeliveryAttempt.update({where:{id:attempt.id},data:{status,lastEventAt:eventAt,deliveredAt:status==="DELIVERED"?eventAt:undefined,failedAt:["FAILED","BOUNCED","UNDELIVERED"].includes(status)?eventAt:undefined}});return{matched:true,duplicate:false};});}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002")return{matched:false,duplicate:true};throw error;}
}

export async function processZenviaWebhook(raw:string,token:string|null,expectedToken:string|undefined){if(!safeHeader(token,expectedToken))throw new Error("INVALID_WEBHOOK_AUTH");const event=JSON.parse(raw) as {id?:string;timestamp?:string;type?:string;messageId?:string;externalId?:string;message?:{id?:string;externalId?:string};status?:string;messageStatus?:{code?:string}};if(event.type!=="MESSAGE_STATUS"||!event.id)throw new Error("INVALID_WEBHOOK_EVENT");const value=(event.status??event.messageStatus?.code??"").toUpperCase();const status:OtpDeliveryStatus=value.includes("DELIVER")?"DELIVERED":value.includes("REJECT")||value.includes("FAIL")?"UNDELIVERED":value.includes("SENT")?"ACCEPTED":"DELAYED";return apply("zenvia",event.id,event.type,event.messageId??event.message?.id,event.externalId??event.message?.externalId,status,new Date(event.timestamp??Date.now()));}

function verifySvix(raw:string,headers:Headers,secret:string|undefined){const id=headers.get("svix-id"),timestamp=headers.get("svix-timestamp"),signature=headers.get("svix-signature");if(!id||!timestamp||!signature||!secret)throw new Error("INVALID_WEBHOOK_AUTH");if(Math.abs(Date.now()/1000-Number(timestamp))>300)throw new Error("INVALID_WEBHOOK_AUTH");const key=Buffer.from(secret.replace(/^whsec_/,""),"base64"),expected=createHmac("sha256",key).update(`${id}.${timestamp}.${raw}`).digest("base64");if(!signature.split(" ").some(part=>part.startsWith("v1,")&&safeHeader(part.slice(3),expected)))throw new Error("INVALID_WEBHOOK_AUTH");return id;}
export async function processResendWebhook(raw:string,headers:Headers,secret:string|undefined){const eventId=verifySvix(raw,headers,secret),event=JSON.parse(raw) as {type?:string;created_at?:string;data?:{email_id?:string}};if(!event.type?.startsWith("email.")||!event.data?.email_id)throw new Error("INVALID_WEBHOOK_EVENT");const statuses:Record<string,OtpDeliveryStatus>={"email.sent":"ACCEPTED","email.delivered":"DELIVERED","email.failed":"FAILED","email.bounced":"BOUNCED","email.delivery_delayed":"DELAYED"};const status=statuses[event.type];if(!status)return{ignored:true};return apply("resend",eventId,event.type,event.data.email_id,undefined,status,new Date(event.created_at??Date.now()));}
