import {createHash,createHmac} from "node:crypto";
import {normalizeE164Brazil} from "./phone";
import type {OtpDeliveryInput,OtpDeliveryProvider,OtpDeliveryResult} from "./otp-provider";
import type {OtpProviderConfig} from "./provider-config";
const API="https://api.zenvia.com/v2";
function classified(status:number,code=`HTTP_${status}`):OtpDeliveryResult{const retryable=status===408||status===429||status>=500;return{accepted:false,retryable,fallbackAllowed:retryable||status===400||status===404,errorCode:code};}
export class ZenviaClient{constructor(private readonly config:OtpProviderConfig,private readonly fetcher:typeof fetch=fetch){}async post(path:string,payload:unknown):Promise<OtpDeliveryResult>{const body=JSON.stringify(payload),headers:Record<string,string>={"Content-Type":"application/json","X-API-Token":this.config.ZENVIA_API_TOKEN!};if(this.config.ZENVIA_API_SECRET){const date=new Date().toUTCString(),signable=`POST\n${createHash("md5").update(body).digest("hex")}\napplication/json\n${date}\napi.zenvia.com\n${path}`;headers.Date=date;headers["X-API-Signature"]=createHmac("sha256",this.config.ZENVIA_API_SECRET).update(signable).digest("base64");}try{const response=await this.fetcher(`${API}${path}`,{method:"POST",headers,body,signal:AbortSignal.timeout(this.config.OTP_PROVIDER_TIMEOUT_MS)}),data=await response.json().catch(()=>({})) as{id?:string;code?:string};if(!response.ok||!data.id)return classified(response.status,data.code);return{accepted:true,retryable:false,providerMessageId:data.id};}catch(error){return{accepted:false,retryable:true,fallbackAllowed:true,errorCode:error instanceof DOMException&&error.name==="TimeoutError"?"TIMEOUT":"NETWORK_ERROR"};}}}
export class ZenviaWhatsAppOtpProvider implements OtpDeliveryProvider{readonly name="zenvia";readonly channel="WHATSAPP" as const;constructor(private readonly config:OtpProviderConfig,private readonly client=new ZenviaClient(config)){}send(input:OtpDeliveryInput){return this.client.post("/channels/whatsapp/messages",{externalId:input.metadata.deliveryAttemptId,from:this.config.ZENVIA_WHATSAPP_FROM,to:normalizeE164Brazil(input.destination),contents:[{type:"template",templateId:this.config.ZENVIA_WHATSAPP_OTP_TEMPLATE_ID,fields:{token:input.code,minutes:String(Math.ceil(input.expiresInSeconds/60))}}]});}}
export class ZenviaSmsOtpProvider implements OtpDeliveryProvider{readonly name="zenvia";readonly channel="SMS" as const;constructor(private readonly config:OtpProviderConfig,private readonly client=new ZenviaClient(config)){}send(input:OtpDeliveryInput){return this.client.post("/channels/sms/messages",{externalId:input.metadata.deliveryAttemptId,from:this.config.ZENVIA_SMS_FROM,to:normalizeE164Brazil(input.destination),contents:[{type:"text",text:`Código de confirmação: ${input.code}. Expira em ${Math.ceil(input.expiresInSeconds/60)} min. Não compartilhe.`}]});}}
